<Solution xmlns:i="http://www.w3.org/2001/XMLSchema-instance" z:Id="i1" xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/" xmlns="http://schemas.datacontract.org/2004/07/NationalInstruments.PackageBuilder.Engine">
    <Name>ClassDAmplifier</Name>
    <SourceItems>
        <SourceItem z:Id="i2">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk Sweep\BuiltUI\Crosstalk Sweep UI.lvlibp</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i3">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk Sweep\Crosstalk Sweep.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i4">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk Sweep\Crosstalk Sweep.exe</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i5">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk Sweep\Crosstalk Sweep.ini</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i6">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk Sweep\Crosstalk Sweep.serviceconfig</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i7">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk Sweep\Libraries\Linux\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i8">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk Sweep\Libraries\LinuxRT\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i9">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk Sweep\Libraries\Win32\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i10">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk Sweep\Libraries\Win64\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i11">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk_Class D Amplifier\BuildUI\Crosstalk UI.lvlibp</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i12">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk_Class D Amplifier\Crosstalk_ClassDAmplifier.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i13">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk_Class D Amplifier\Crosstalk_ClassDAmplifier.exe</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i14">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk_Class D Amplifier\Crosstalk_ClassDAmplifier.ini</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i15">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk_Class D Amplifier\Crosstalk_ClassDAmplifier.serviceconfig</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i16">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk_Class D Amplifier\Libraries\Linux\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i17">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk_Class D Amplifier\Libraries\LinuxRT\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i18">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk_Class D Amplifier\Libraries\Win32\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i19">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk_Class D Amplifier\Libraries\Win64\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i20">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency Sweep_Class D Amplifier\BuildUI\Efficiency Sweep UI.lvlibp</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i21">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency Sweep_Class D Amplifier\Efficinecy Sweep_Class D Amplifier.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i22">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency Sweep_Class D Amplifier\Efficinecy Sweep_Class D Amplifier.exe</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i23">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency Sweep_Class D Amplifier\Efficinecy Sweep_Class D Amplifier.ini</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i24">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency Sweep_Class D Amplifier\Efficinecy Sweep_Class D Amplifier.serviceconfig</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i25">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency Sweep_Class D Amplifier\Libraries\Linux\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i26">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency Sweep_Class D Amplifier\Libraries\LinuxRT\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i27">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency Sweep_Class D Amplifier\Libraries\Win32\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i28">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency Sweep_Class D Amplifier\Libraries\Win64\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i29">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency_Class D Amplifier\BuiltUI\Efficiency_Class D Amplifier_UI.lvlibp</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i30">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency_Class D Amplifier\Efficiency_Class D Amplifier.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i31">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency_Class D Amplifier\Efficiency_Class D Amplifier.exe</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i32">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency_Class D Amplifier\Efficiency_Class D Amplifier.ini</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i33">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency_Class D Amplifier\Efficiency_Class D Amplifier.serviceconfig</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i34">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency_Class D Amplifier\Libraries\Linux\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i35">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency_Class D Amplifier\Libraries\LinuxRT\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i36">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency_Class D Amplifier\Libraries\Win32\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i37">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency_Class D Amplifier\Libraries\Win64\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i38">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Generation_Class D Amplifier\BuiltUI\Generation_Class D Amplifier_UI.lvlibp</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i39">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Generation_Class D Amplifier\Generation_Class D Amplifier.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i40">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Generation_Class D Amplifier\Generation_Class D Amplifier.exe</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i41">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Generation_Class D Amplifier\Generation_Class D Amplifier.ini</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i42">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Generation_Class D Amplifier\Generation_Class D Amplifier.serviceconfig</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i43">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Generation_Class D Amplifier\Libraries\Linux\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i44">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Generation_Class D Amplifier\Libraries\LinuxRT\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i45">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Generation_Class D Amplifier\Libraries\Win32\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i46">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Generation_Class D Amplifier\Libraries\Win64\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i47">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Noise Sweep_Class D Amplifier\BuildUI\Noise Sweep UI.lvlibp</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i48">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Noise Sweep_Class D Amplifier\Libraries\Linux\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i49">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Noise Sweep_Class D Amplifier\Libraries\LinuxRT\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i50">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Noise Sweep_Class D Amplifier\Libraries\Win32\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i51">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Noise Sweep_Class D Amplifier\Libraries\Win64\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i52">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Noise Sweep_Class D Amplifier\Noise Sweep_Class D Amplifier.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i53">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Noise Sweep_Class D Amplifier\Noise Sweep_Class D Amplifier.exe</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i54">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Noise Sweep_Class D Amplifier\Noise Sweep_Class D Amplifier.ini</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i55">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Noise Sweep_Class D Amplifier\Noise Sweep_Class D Amplifier.serviceconfig</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i56">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\services\Audio Generation Service\AudioGenerationService.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i57">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\services\Audio Generation Service\AudioGenerationService.exe</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i58">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\services\Audio Generation Service\AudioGenerationService.ini</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i59">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\services\Utility\DeleteServices_Audio.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i60">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\services\Utility\DeleteServices_Audio.exe</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i61">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\services\Utility\DeleteServices_Audio.ini</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i62">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\services\Utility\RegisterServices_Audio.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i63">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\services\Utility\RegisterServices_Audio.exe</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i64">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\services\Utility\RegisterServices_Audio.ini</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i65">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\services\Utility\srvany.exe</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i66">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone No Gen_Class D Amplifier\BuiltUI\Single Tone No Gen_Class D Amplifier_UI.lvlibp</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i67">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone No Gen_Class D Amplifier\Libraries\Linux\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i68">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone No Gen_Class D Amplifier\Libraries\LinuxRT\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i69">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone No Gen_Class D Amplifier\Libraries\Win32\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i70">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone No Gen_Class D Amplifier\Libraries\Win64\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i71">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone No Gen_Class D Amplifier\Single Tone No Gen_Class D Amplifier.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i72">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone No Gen_Class D Amplifier\Single Tone No Gen_Class D Amplifier.exe</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i73">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone No Gen_Class D Amplifier\Single Tone No Gen_Class D Amplifier.ini</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i74">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone No Gen_Class D Amplifier\Single Tone No Gen_Class D Amplifier.serviceconfig</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i75">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone Power Sweep\BuiltUI\Single Tone Power Sweep UI.lvlibp</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i76">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone Power Sweep\Libraries\Linux\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i77">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone Power Sweep\Libraries\LinuxRT\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i78">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone Power Sweep\Libraries\Win32\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i79">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone Power Sweep\Libraries\Win64\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i80">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone Power Sweep\Single Tone Power Sweep.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i81">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone Power Sweep\Single Tone Power Sweep.exe</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i82">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone Power Sweep\Single Tone Power Sweep.ini</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i83">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone Power Sweep\Single Tone Power Sweep.serviceconfig</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i84">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone_Class D Amplifier\BuiltUI\Single Tone_Class D Amplifier_UI.lvlibp</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i85">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone_Class D Amplifier\Libraries\Linux\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i86">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone_Class D Amplifier\Libraries\LinuxRT\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i87">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone_Class D Amplifier\Libraries\Win32\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i88">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone_Class D Amplifier\Libraries\Win64\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i89">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone_Class D Amplifier\Single Tone_Class D Amplifier.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i90">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone_Class D Amplifier\Single Tone_Class D Amplifier.exe</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i91">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone_Class D Amplifier\Single Tone_Class D Amplifier.ini</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i92">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone_Class D Amplifier\Single Tone_Class D Amplifier.serviceconfig</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i93">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Stepped Frequency Sweep_Class D Amplifier\BuildUI\Stepped Frequency Sweep UI.lvlibp</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i94">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Stepped Frequency Sweep_Class D Amplifier\Libraries\Linux\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i95">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Stepped Frequency Sweep_Class D Amplifier\Libraries\LinuxRT\liblabview_grpc_server.so</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i96">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Stepped Frequency Sweep_Class D Amplifier\Libraries\Win32\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i97">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Stepped Frequency Sweep_Class D Amplifier\Libraries\Win64\labview_grpc_server.dll</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i98">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Stepped Frequency Sweep_Class D Amplifier\Stepped Sweep_Class D Amplifier.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i99">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Stepped Frequency Sweep_Class D Amplifier\Stepped Sweep_Class D Amplifier.exe</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i100">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Stepped Frequency Sweep_Class D Amplifier\Stepped Sweep_Class D Amplifier.ini</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i101">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Stepped Frequency Sweep_Class D Amplifier\Stepped Sweep_Class D Amplifier.serviceconfig</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i102">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk Sweep\BuiltUI</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i2" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i103">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk Sweep\Libraries\Linux</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i7" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i104">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk Sweep\Libraries\LinuxRT</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i8" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i105">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk Sweep\Libraries\Win32</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i9" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i106">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk Sweep\Libraries\Win64</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i10" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i107">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk_Class D Amplifier\BuildUI</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i11" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i108">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk_Class D Amplifier\Libraries\Linux</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i16" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i109">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk_Class D Amplifier\Libraries\LinuxRT</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i17" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i110">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk_Class D Amplifier\Libraries\Win32</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i18" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i111">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk_Class D Amplifier\Libraries\Win64</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i19" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i112">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency Sweep_Class D Amplifier\BuildUI</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i20" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i113">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency Sweep_Class D Amplifier\Libraries\Linux</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i25" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i114">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency Sweep_Class D Amplifier\Libraries\LinuxRT</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i26" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i115">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency Sweep_Class D Amplifier\Libraries\Win32</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i27" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i116">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency Sweep_Class D Amplifier\Libraries\Win64</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i28" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i117">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency_Class D Amplifier\BuiltUI</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i29" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i118">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency_Class D Amplifier\Libraries\Linux</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i34" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i119">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency_Class D Amplifier\Libraries\LinuxRT</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i35" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i120">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency_Class D Amplifier\Libraries\Win32</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i36" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i121">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency_Class D Amplifier\Libraries\Win64</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i37" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i122">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Generation_Class D Amplifier\BuiltUI</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i38" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i123">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Generation_Class D Amplifier\Libraries\Linux</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i43" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i124">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Generation_Class D Amplifier\Libraries\LinuxRT</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i44" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i125">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Generation_Class D Amplifier\Libraries\Win32</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i45" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i126">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Generation_Class D Amplifier\Libraries\Win64</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i46" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i127">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Noise Sweep_Class D Amplifier\BuildUI</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i47" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i128">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Noise Sweep_Class D Amplifier\Libraries\Linux</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i48" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i129">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Noise Sweep_Class D Amplifier\Libraries\LinuxRT</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i49" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i130">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Noise Sweep_Class D Amplifier\Libraries\Win32</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i50" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i131">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Noise Sweep_Class D Amplifier\Libraries\Win64</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i51" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i132">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone No Gen_Class D Amplifier\BuiltUI</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i66" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i133">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone No Gen_Class D Amplifier\Libraries\Linux</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i67" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i134">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone No Gen_Class D Amplifier\Libraries\LinuxRT</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i68" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i135">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone No Gen_Class D Amplifier\Libraries\Win32</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i69" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i136">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone No Gen_Class D Amplifier\Libraries\Win64</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i70" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i137">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone Power Sweep\BuiltUI</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i75" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i138">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone Power Sweep\Libraries\Linux</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i76" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i139">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone Power Sweep\Libraries\LinuxRT</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i77" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i140">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone Power Sweep\Libraries\Win32</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i78" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i141">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone Power Sweep\Libraries\Win64</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i79" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i142">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone_Class D Amplifier\BuiltUI</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i84" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i143">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone_Class D Amplifier\Libraries\Linux</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i85" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i144">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone_Class D Amplifier\Libraries\LinuxRT</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i86" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i145">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone_Class D Amplifier\Libraries\Win32</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i87" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i146">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone_Class D Amplifier\Libraries\Win64</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i88" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i147">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Stepped Frequency Sweep_Class D Amplifier\BuildUI</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i93" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i148">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Stepped Frequency Sweep_Class D Amplifier\Libraries\Linux</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i94" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i149">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Stepped Frequency Sweep_Class D Amplifier\Libraries\LinuxRT</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i95" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i150">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Stepped Frequency Sweep_Class D Amplifier\Libraries\Win32</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i96" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i151">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Stepped Frequency Sweep_Class D Amplifier\Libraries\Win64</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i97" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i152">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\services\Audio Generation Service</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i56" />
                <SourceItem z:Ref="i57" />
                <SourceItem z:Ref="i58" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i153">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\services\Utility</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i59" />
                <SourceItem z:Ref="i60" />
                <SourceItem z:Ref="i61" />
                <SourceItem z:Ref="i62" />
                <SourceItem z:Ref="i63" />
                <SourceItem z:Ref="i64" />
                <SourceItem z:Ref="i65" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i154">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\services</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i152" />
                <SourceItem z:Ref="i153" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i155">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk Sweep\Libraries</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i103" />
                <SourceItem z:Ref="i104" />
                <SourceItem z:Ref="i105" />
                <SourceItem z:Ref="i106" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i156">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk_Class D Amplifier\Libraries</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i108" />
                <SourceItem z:Ref="i109" />
                <SourceItem z:Ref="i110" />
                <SourceItem z:Ref="i111" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i157">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency Sweep_Class D Amplifier\Libraries</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i113" />
                <SourceItem z:Ref="i114" />
                <SourceItem z:Ref="i115" />
                <SourceItem z:Ref="i116" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i158">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency_Class D Amplifier\Libraries</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i118" />
                <SourceItem z:Ref="i119" />
                <SourceItem z:Ref="i120" />
                <SourceItem z:Ref="i121" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i159">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Generation_Class D Amplifier\Libraries</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i123" />
                <SourceItem z:Ref="i124" />
                <SourceItem z:Ref="i125" />
                <SourceItem z:Ref="i126" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i160">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Noise Sweep_Class D Amplifier\Libraries</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i128" />
                <SourceItem z:Ref="i129" />
                <SourceItem z:Ref="i130" />
                <SourceItem z:Ref="i131" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i161">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone No Gen_Class D Amplifier\Libraries</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i133" />
                <SourceItem z:Ref="i134" />
                <SourceItem z:Ref="i135" />
                <SourceItem z:Ref="i136" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i162">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone Power Sweep\Libraries</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i138" />
                <SourceItem z:Ref="i139" />
                <SourceItem z:Ref="i140" />
                <SourceItem z:Ref="i141" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i163">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone_Class D Amplifier\Libraries</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i143" />
                <SourceItem z:Ref="i144" />
                <SourceItem z:Ref="i145" />
                <SourceItem z:Ref="i146" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i164">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Stepped Frequency Sweep_Class D Amplifier\Libraries</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i148" />
                <SourceItem z:Ref="i149" />
                <SourceItem z:Ref="i150" />
                <SourceItem z:Ref="i151" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i165">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk Sweep</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i3" />
                <SourceItem z:Ref="i4" />
                <SourceItem z:Ref="i5" />
                <SourceItem z:Ref="i6" />
                <SourceItem z:Ref="i102" />
                <SourceItem z:Ref="i155" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i166">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Crosstalk_Class D Amplifier</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i12" />
                <SourceItem z:Ref="i13" />
                <SourceItem z:Ref="i14" />
                <SourceItem z:Ref="i15" />
                <SourceItem z:Ref="i156" />
                <SourceItem z:Ref="i107" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i167">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency Sweep_Class D Amplifier</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i21" />
                <SourceItem z:Ref="i22" />
                <SourceItem z:Ref="i23" />
                <SourceItem z:Ref="i24" />
                <SourceItem z:Ref="i112" />
                <SourceItem z:Ref="i157" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i168">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Efficiency_Class D Amplifier</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i30" />
                <SourceItem z:Ref="i31" />
                <SourceItem z:Ref="i32" />
                <SourceItem z:Ref="i33" />
                <SourceItem z:Ref="i117" />
                <SourceItem z:Ref="i158" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i169">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Generation_Class D Amplifier</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i39" />
                <SourceItem z:Ref="i40" />
                <SourceItem z:Ref="i41" />
                <SourceItem z:Ref="i42" />
                <SourceItem z:Ref="i122" />
                <SourceItem z:Ref="i159" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i170">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Noise Sweep_Class D Amplifier</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i52" />
                <SourceItem z:Ref="i53" />
                <SourceItem z:Ref="i54" />
                <SourceItem z:Ref="i55" />
                <SourceItem z:Ref="i127" />
                <SourceItem z:Ref="i160" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i171">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone No Gen_Class D Amplifier</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i71" />
                <SourceItem z:Ref="i72" />
                <SourceItem z:Ref="i73" />
                <SourceItem z:Ref="i74" />
                <SourceItem z:Ref="i132" />
                <SourceItem z:Ref="i161" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i172">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone Power Sweep</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i80" />
                <SourceItem z:Ref="i81" />
                <SourceItem z:Ref="i82" />
                <SourceItem z:Ref="i83" />
                <SourceItem z:Ref="i137" />
                <SourceItem z:Ref="i162" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i173">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Single Tone_Class D Amplifier</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i89" />
                <SourceItem z:Ref="i90" />
                <SourceItem z:Ref="i91" />
                <SourceItem z:Ref="i92" />
                <SourceItem z:Ref="i142" />
                <SourceItem z:Ref="i163" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i174">
            <PluginConfigurationOptions />
            <RelativePath>..\builds\Stepped Frequency Sweep_Class D Amplifier</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i98" />
                <SourceItem z:Ref="i99" />
                <SourceItem z:Ref="i100" />
                <SourceItem z:Ref="i101" />
                <SourceItem z:Ref="i164" />
                <SourceItem z:Ref="i147" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i175">
            <PluginConfigurationOptions />
            <RelativePath>..\builds</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i166" />
                <SourceItem z:Ref="i174" />
                <SourceItem z:Ref="i173" />
                <SourceItem z:Ref="i167" />
                <SourceItem z:Ref="i168" />
                <SourceItem z:Ref="i169" />
                <SourceItem z:Ref="i154" />
                <SourceItem z:Ref="i171" />
                <SourceItem z:Ref="i165" />
                <SourceItem z:Ref="i170" />
                <SourceItem z:Ref="i172" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
    </SourceItems>
    <InputSourceItems>
        <SourceItem z:Ref="i175" />
    </InputSourceItems>
    <Distributions>
        <Distribution z:Id="i176" i:type="Package">
            <DistributionItems>
                <DistributionItem z:Id="i177" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments</DestinationRelativePath>
                    <Name>National Instruments</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i178" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink</DestinationRelativePath>
                    <Name>MeasurementLink</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i179" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services</DestinationRelativePath>
                    <Name>Services</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i180" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier</DestinationRelativePath>
                    <Name>Class D Amplifier</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i181" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk_Class D Amplifier</DestinationRelativePath>
                    <Name>Crosstalk_Class D Amplifier</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i182" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk_Class D Amplifier\Crosstalk_ClassDAmplifier.aliases</DestinationRelativePath>
                    <Name>Crosstalk_ClassDAmplifier.aliases</Name>
                    <SourceItem z:Ref="i12" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i183" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk_Class D Amplifier\Crosstalk_ClassDAmplifier.ini</DestinationRelativePath>
                    <Name>Crosstalk_ClassDAmplifier.ini</Name>
                    <SourceItem z:Ref="i14" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i184" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk_Class D Amplifier\Crosstalk_ClassDAmplifier.serviceconfig</DestinationRelativePath>
                    <Name>Crosstalk_ClassDAmplifier.serviceconfig</Name>
                    <SourceItem z:Ref="i15" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i185" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk_Class D Amplifier\Libraries</DestinationRelativePath>
                    <Name>Libraries</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i186" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk_Class D Amplifier\Libraries\Linux</DestinationRelativePath>
                    <Name>Linux</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i187" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk_Class D Amplifier\Libraries\Linux\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i16" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i188" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk_Class D Amplifier\Libraries\LinuxRT</DestinationRelativePath>
                    <Name>LinuxRT</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i189" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk_Class D Amplifier\Libraries\LinuxRT\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i17" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i190" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk_Class D Amplifier\Libraries\Win32</DestinationRelativePath>
                    <Name>Win32</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i191" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk_Class D Amplifier\Libraries\Win32\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i18" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i192" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk_Class D Amplifier\Libraries\Win64</DestinationRelativePath>
                    <Name>Win64</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i193" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk_Class D Amplifier\Libraries\Win64\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i19" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i194" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk_Class D Amplifier\BuildUI</DestinationRelativePath>
                    <Name>BuildUI</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i195" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk_Class D Amplifier\BuildUI\Crosstalk UI.lvlibp</DestinationRelativePath>
                    <Name>Crosstalk UI.lvlibp</Name>
                    <SourceItem z:Ref="i11" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i196" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone_Class D Amplifier</DestinationRelativePath>
                    <Name>Single Tone_Class D Amplifier</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i197" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone_Class D Amplifier\Single Tone_Class D Amplifier.aliases</DestinationRelativePath>
                    <Name>Single Tone_Class D Amplifier.aliases</Name>
                    <SourceItem z:Ref="i89" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i198" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone_Class D Amplifier\Single Tone_Class D Amplifier.exe</DestinationRelativePath>
                    <Name>Single Tone_Class D Amplifier.exe</Name>
                    <SourceItem z:Ref="i90" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i199" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone_Class D Amplifier\Single Tone_Class D Amplifier.ini</DestinationRelativePath>
                    <Name>Single Tone_Class D Amplifier.ini</Name>
                    <SourceItem z:Ref="i91" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i200" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone_Class D Amplifier\Single Tone_Class D Amplifier.serviceconfig</DestinationRelativePath>
                    <Name>Single Tone_Class D Amplifier.serviceconfig</Name>
                    <SourceItem z:Ref="i92" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i201" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone_Class D Amplifier\BuiltUI</DestinationRelativePath>
                    <Name>BuiltUI</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i202" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone_Class D Amplifier\BuiltUI\Single Tone_Class D Amplifier_UI.lvlibp</DestinationRelativePath>
                    <Name>Single Tone_Class D Amplifier_UI.lvlibp</Name>
                    <SourceItem z:Ref="i84" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i203" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone_Class D Amplifier\Libraries</DestinationRelativePath>
                    <Name>Libraries</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i204" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone_Class D Amplifier\Libraries\Linux</DestinationRelativePath>
                    <Name>Linux</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i205" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone_Class D Amplifier\Libraries\Linux\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i85" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i206" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone_Class D Amplifier\Libraries\LinuxRT</DestinationRelativePath>
                    <Name>LinuxRT</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i207" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone_Class D Amplifier\Libraries\LinuxRT\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i86" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i208" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone_Class D Amplifier\Libraries\Win32</DestinationRelativePath>
                    <Name>Win32</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i209" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone_Class D Amplifier\Libraries\Win32\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i87" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i210" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone_Class D Amplifier\Libraries\Win64</DestinationRelativePath>
                    <Name>Win64</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i211" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone_Class D Amplifier\Libraries\Win64\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i88" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i212" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Stepped Frequency Sweep_Class D Amplifier</DestinationRelativePath>
                    <Name>Stepped Frequency Sweep_Class D Amplifier</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i213" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Stepped Frequency Sweep_Class D Amplifier\Stepped Sweep_Class D Amplifier.aliases</DestinationRelativePath>
                    <Name>Stepped Sweep_Class D Amplifier.aliases</Name>
                    <SourceItem z:Ref="i98" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i214" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Stepped Frequency Sweep_Class D Amplifier\Stepped Sweep_Class D Amplifier.exe</DestinationRelativePath>
                    <Name>Stepped Sweep_Class D Amplifier.exe</Name>
                    <SourceItem z:Ref="i99" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i215" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Stepped Frequency Sweep_Class D Amplifier\Stepped Sweep_Class D Amplifier.ini</DestinationRelativePath>
                    <Name>Stepped Sweep_Class D Amplifier.ini</Name>
                    <SourceItem z:Ref="i100" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i216" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Stepped Frequency Sweep_Class D Amplifier\Stepped Sweep_Class D Amplifier.serviceconfig</DestinationRelativePath>
                    <Name>Stepped Sweep_Class D Amplifier.serviceconfig</Name>
                    <SourceItem z:Ref="i101" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i217" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Stepped Frequency Sweep_Class D Amplifier\Libraries</DestinationRelativePath>
                    <Name>Libraries</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i218" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Stepped Frequency Sweep_Class D Amplifier\Libraries\Linux</DestinationRelativePath>
                    <Name>Linux</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i219" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Stepped Frequency Sweep_Class D Amplifier\Libraries\Linux\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i94" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i220" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Stepped Frequency Sweep_Class D Amplifier\Libraries\LinuxRT</DestinationRelativePath>
                    <Name>LinuxRT</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i221" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Stepped Frequency Sweep_Class D Amplifier\Libraries\LinuxRT\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i95" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i222" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Stepped Frequency Sweep_Class D Amplifier\Libraries\Win32</DestinationRelativePath>
                    <Name>Win32</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i223" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Stepped Frequency Sweep_Class D Amplifier\Libraries\Win32\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i96" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i224" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Stepped Frequency Sweep_Class D Amplifier\Libraries\Win64</DestinationRelativePath>
                    <Name>Win64</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i225" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Stepped Frequency Sweep_Class D Amplifier\Libraries\Win64\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i97" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i226" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Stepped Frequency Sweep_Class D Amplifier\BuildUI</DestinationRelativePath>
                    <Name>BuildUI</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i227" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Stepped Frequency Sweep_Class D Amplifier\BuildUI\Stepped Frequency Sweep UI.lvlibp</DestinationRelativePath>
                    <Name>Stepped Frequency Sweep UI.lvlibp</Name>
                    <SourceItem z:Ref="i93" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i228" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk_Class D Amplifier\Crosstalk_ClassDAmplifier.exe</DestinationRelativePath>
                    <Name>Crosstalk_ClassDAmplifier.exe</Name>
                    <SourceItem z:Ref="i13" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i229" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency Sweep_Class D Amplifier</DestinationRelativePath>
                    <Name>Efficiency Sweep_Class D Amplifier</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i230" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency Sweep_Class D Amplifier\Efficinecy Sweep_Class D Amplifier.aliases</DestinationRelativePath>
                    <Name>Efficinecy Sweep_Class D Amplifier.aliases</Name>
                    <SourceItem z:Ref="i21" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i231" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency Sweep_Class D Amplifier\Efficinecy Sweep_Class D Amplifier.exe</DestinationRelativePath>
                    <Name>Efficinecy Sweep_Class D Amplifier.exe</Name>
                    <SourceItem z:Ref="i22" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i232" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency Sweep_Class D Amplifier\Efficinecy Sweep_Class D Amplifier.ini</DestinationRelativePath>
                    <Name>Efficinecy Sweep_Class D Amplifier.ini</Name>
                    <SourceItem z:Ref="i23" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i233" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency Sweep_Class D Amplifier\Efficinecy Sweep_Class D Amplifier.serviceconfig</DestinationRelativePath>
                    <Name>Efficinecy Sweep_Class D Amplifier.serviceconfig</Name>
                    <SourceItem z:Ref="i24" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i234" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency Sweep_Class D Amplifier\BuildUI</DestinationRelativePath>
                    <Name>BuildUI</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i235" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency Sweep_Class D Amplifier\BuildUI\Efficiency Sweep UI.lvlibp</DestinationRelativePath>
                    <Name>Efficiency Sweep UI.lvlibp</Name>
                    <SourceItem z:Ref="i20" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i236" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency Sweep_Class D Amplifier\Libraries</DestinationRelativePath>
                    <Name>Libraries</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i237" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency Sweep_Class D Amplifier\Libraries\Linux</DestinationRelativePath>
                    <Name>Linux</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i238" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency Sweep_Class D Amplifier\Libraries\Linux\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i25" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i239" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency Sweep_Class D Amplifier\Libraries\LinuxRT</DestinationRelativePath>
                    <Name>LinuxRT</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i240" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency Sweep_Class D Amplifier\Libraries\LinuxRT\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i26" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i241" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency Sweep_Class D Amplifier\Libraries\Win32</DestinationRelativePath>
                    <Name>Win32</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i242" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency Sweep_Class D Amplifier\Libraries\Win32\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i27" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i243" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency Sweep_Class D Amplifier\Libraries\Win64</DestinationRelativePath>
                    <Name>Win64</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i244" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency Sweep_Class D Amplifier\Libraries\Win64\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i28" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i245" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency_Class D Amplifier</DestinationRelativePath>
                    <Name>Efficiency_Class D Amplifier</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i246" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency_Class D Amplifier\Efficiency_Class D Amplifier.aliases</DestinationRelativePath>
                    <Name>Efficiency_Class D Amplifier.aliases</Name>
                    <SourceItem z:Ref="i30" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i247" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency_Class D Amplifier\Efficiency_Class D Amplifier.exe</DestinationRelativePath>
                    <Name>Efficiency_Class D Amplifier.exe</Name>
                    <SourceItem z:Ref="i31" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i248" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency_Class D Amplifier\Efficiency_Class D Amplifier.ini</DestinationRelativePath>
                    <Name>Efficiency_Class D Amplifier.ini</Name>
                    <SourceItem z:Ref="i32" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i249" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency_Class D Amplifier\Efficiency_Class D Amplifier.serviceconfig</DestinationRelativePath>
                    <Name>Efficiency_Class D Amplifier.serviceconfig</Name>
                    <SourceItem z:Ref="i33" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i250" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency_Class D Amplifier\BuiltUI</DestinationRelativePath>
                    <Name>BuiltUI</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i251" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency_Class D Amplifier\BuiltUI\Efficiency_Class D Amplifier_UI.lvlibp</DestinationRelativePath>
                    <Name>Efficiency_Class D Amplifier_UI.lvlibp</Name>
                    <SourceItem z:Ref="i29" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i252" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency_Class D Amplifier\Libraries</DestinationRelativePath>
                    <Name>Libraries</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i253" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency_Class D Amplifier\Libraries\Linux</DestinationRelativePath>
                    <Name>Linux</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i254" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency_Class D Amplifier\Libraries\Linux\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i34" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i255" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency_Class D Amplifier\Libraries\LinuxRT</DestinationRelativePath>
                    <Name>LinuxRT</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i256" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency_Class D Amplifier\Libraries\LinuxRT\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i35" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i257" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency_Class D Amplifier\Libraries\Win32</DestinationRelativePath>
                    <Name>Win32</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i258" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency_Class D Amplifier\Libraries\Win32\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i36" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i259" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency_Class D Amplifier\Libraries\Win64</DestinationRelativePath>
                    <Name>Win64</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i260" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Efficiency_Class D Amplifier\Libraries\Win64\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i37" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i261" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Generation_Class D Amplifier</DestinationRelativePath>
                    <Name>Generation_Class D Amplifier</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i262" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Generation_Class D Amplifier\Generation_Class D Amplifier.aliases</DestinationRelativePath>
                    <Name>Generation_Class D Amplifier.aliases</Name>
                    <SourceItem z:Ref="i39" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i263" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Generation_Class D Amplifier\Generation_Class D Amplifier.exe</DestinationRelativePath>
                    <Name>Generation_Class D Amplifier.exe</Name>
                    <SourceItem z:Ref="i40" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i264" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Generation_Class D Amplifier\Generation_Class D Amplifier.ini</DestinationRelativePath>
                    <Name>Generation_Class D Amplifier.ini</Name>
                    <SourceItem z:Ref="i41" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i265" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Generation_Class D Amplifier\Generation_Class D Amplifier.serviceconfig</DestinationRelativePath>
                    <Name>Generation_Class D Amplifier.serviceconfig</Name>
                    <SourceItem z:Ref="i42" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i266" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Generation_Class D Amplifier\BuiltUI</DestinationRelativePath>
                    <Name>BuiltUI</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i267" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Generation_Class D Amplifier\BuiltUI\Generation_Class D Amplifier_UI.lvlibp</DestinationRelativePath>
                    <Name>Generation_Class D Amplifier_UI.lvlibp</Name>
                    <SourceItem z:Ref="i38" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i268" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Generation_Class D Amplifier\Libraries</DestinationRelativePath>
                    <Name>Libraries</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i269" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Generation_Class D Amplifier\Libraries\Linux</DestinationRelativePath>
                    <Name>Linux</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i270" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Generation_Class D Amplifier\Libraries\Linux\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i43" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i271" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Generation_Class D Amplifier\Libraries\LinuxRT</DestinationRelativePath>
                    <Name>LinuxRT</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i272" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Generation_Class D Amplifier\Libraries\LinuxRT\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i44" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i273" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Generation_Class D Amplifier\Libraries\Win32</DestinationRelativePath>
                    <Name>Win32</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i274" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Generation_Class D Amplifier\Libraries\Win32\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i45" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i275" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Generation_Class D Amplifier\Libraries\Win64</DestinationRelativePath>
                    <Name>Win64</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i276" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Generation_Class D Amplifier\Libraries\Win64\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i46" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i277" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[Program Files (64-bit)]\AudioValidation</DestinationRelativePath>
                    <Name>AudioValidation</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i278" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[Program Files (64-bit)]\AudioValidation\Utility</DestinationRelativePath>
                    <Name>Utility</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i279" i:type="DistributionFileItem">
                    <DestinationRelativePath>[Program Files (64-bit)]\AudioValidation\AudioGenerationService.aliases</DestinationRelativePath>
                    <Name>AudioGenerationService.aliases</Name>
                    <SourceItem z:Ref="i56" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i280" i:type="DistributionFileItem">
                    <DestinationRelativePath>[Program Files (64-bit)]\AudioValidation\AudioGenerationService.exe</DestinationRelativePath>
                    <Name>AudioGenerationService.exe</Name>
                    <SourceItem z:Ref="i57" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i281" i:type="DistributionFileItem">
                    <DestinationRelativePath>[Program Files (64-bit)]\AudioValidation\AudioGenerationService.ini</DestinationRelativePath>
                    <Name>AudioGenerationService.ini</Name>
                    <SourceItem z:Ref="i58" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i282" i:type="DistributionFileItem">
                    <DestinationRelativePath>[Program Files (64-bit)]\AudioValidation\Utility\DeleteServices_Audio.aliases</DestinationRelativePath>
                    <Name>DeleteServices_Audio.aliases</Name>
                    <SourceItem z:Ref="i59" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i283" i:type="DistributionFileItem">
                    <DestinationRelativePath>[Program Files (64-bit)]\AudioValidation\Utility\DeleteServices_Audio.exe</DestinationRelativePath>
                    <Name>DeleteServices_Audio.exe</Name>
                    <SourceItem z:Ref="i60" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i284" i:type="DistributionFileItem">
                    <DestinationRelativePath>[Program Files (64-bit)]\AudioValidation\Utility\DeleteServices_Audio.ini</DestinationRelativePath>
                    <Name>DeleteServices_Audio.ini</Name>
                    <SourceItem z:Ref="i61" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i285" i:type="DistributionFileItem">
                    <DestinationRelativePath>[Program Files (64-bit)]\AudioValidation\Utility\RegisterServices_Audio.aliases</DestinationRelativePath>
                    <Name>RegisterServices_Audio.aliases</Name>
                    <SourceItem z:Ref="i62" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i286" i:type="DistributionFileItem">
                    <DestinationRelativePath>[Program Files (64-bit)]\AudioValidation\Utility\RegisterServices_Audio.exe</DestinationRelativePath>
                    <Name>RegisterServices_Audio.exe</Name>
                    <SourceItem z:Ref="i63" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i287" i:type="DistributionFileItem">
                    <DestinationRelativePath>[Program Files (64-bit)]\AudioValidation\Utility\RegisterServices_Audio.ini</DestinationRelativePath>
                    <Name>RegisterServices_Audio.ini</Name>
                    <SourceItem z:Ref="i64" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i288" i:type="DistributionFileItem">
                    <DestinationRelativePath>[Program Files (64-bit)]\AudioValidation\Utility\srvany.exe</DestinationRelativePath>
                    <Name>srvany.exe</Name>
                    <SourceItem z:Ref="i65" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i289" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone No Gen_Class D Amplifier</DestinationRelativePath>
                    <Name>Single Tone No Gen_Class D Amplifier</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i290" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone No Gen_Class D Amplifier\Single Tone No Gen_Class D Amplifier.aliases</DestinationRelativePath>
                    <Name>Single Tone No Gen_Class D Amplifier.aliases</Name>
                    <SourceItem z:Ref="i71" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i291" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone No Gen_Class D Amplifier\Single Tone No Gen_Class D Amplifier.exe</DestinationRelativePath>
                    <Name>Single Tone No Gen_Class D Amplifier.exe</Name>
                    <SourceItem z:Ref="i72" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i292" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone No Gen_Class D Amplifier\Single Tone No Gen_Class D Amplifier.ini</DestinationRelativePath>
                    <Name>Single Tone No Gen_Class D Amplifier.ini</Name>
                    <SourceItem z:Ref="i73" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i293" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone No Gen_Class D Amplifier\Single Tone No Gen_Class D Amplifier.serviceconfig</DestinationRelativePath>
                    <Name>Single Tone No Gen_Class D Amplifier.serviceconfig</Name>
                    <SourceItem z:Ref="i74" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i294" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone No Gen_Class D Amplifier\BuiltUI</DestinationRelativePath>
                    <Name>BuiltUI</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i295" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone No Gen_Class D Amplifier\BuiltUI\Single Tone No Gen_Class D Amplifier_UI.lvlibp</DestinationRelativePath>
                    <Name>Single Tone No Gen_Class D Amplifier_UI.lvlibp</Name>
                    <SourceItem z:Ref="i66" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i296" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone No Gen_Class D Amplifier\Libraries</DestinationRelativePath>
                    <Name>Libraries</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i297" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone No Gen_Class D Amplifier\Libraries\Linux</DestinationRelativePath>
                    <Name>Linux</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i298" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone No Gen_Class D Amplifier\Libraries\Linux\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i67" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i299" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone No Gen_Class D Amplifier\Libraries\LinuxRT</DestinationRelativePath>
                    <Name>LinuxRT</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i300" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone No Gen_Class D Amplifier\Libraries\LinuxRT\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i68" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i301" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone No Gen_Class D Amplifier\Libraries\Win32</DestinationRelativePath>
                    <Name>Win32</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i302" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone No Gen_Class D Amplifier\Libraries\Win32\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i69" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i303" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone No Gen_Class D Amplifier\Libraries\Win64</DestinationRelativePath>
                    <Name>Win64</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i304" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone No Gen_Class D Amplifier\Libraries\Win64\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i70" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i305" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk Sweep</DestinationRelativePath>
                    <Name>Crosstalk Sweep</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i306" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk Sweep\Crosstalk Sweep.aliases</DestinationRelativePath>
                    <Name>Crosstalk Sweep.aliases</Name>
                    <SourceItem z:Ref="i3" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i307" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk Sweep\Crosstalk Sweep.exe</DestinationRelativePath>
                    <Name>Crosstalk Sweep.exe</Name>
                    <SourceItem z:Ref="i4" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i308" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk Sweep\Crosstalk Sweep.ini</DestinationRelativePath>
                    <Name>Crosstalk Sweep.ini</Name>
                    <SourceItem z:Ref="i5" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i309" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk Sweep\Crosstalk Sweep.serviceconfig</DestinationRelativePath>
                    <Name>Crosstalk Sweep.serviceconfig</Name>
                    <SourceItem z:Ref="i6" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i310" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk Sweep\BuiltUI</DestinationRelativePath>
                    <Name>BuiltUI</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i311" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk Sweep\BuiltUI\Crosstalk Sweep UI.lvlibp</DestinationRelativePath>
                    <Name>Crosstalk Sweep UI.lvlibp</Name>
                    <SourceItem z:Ref="i2" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i312" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk Sweep\Libraries</DestinationRelativePath>
                    <Name>Libraries</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i313" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk Sweep\Libraries\Linux</DestinationRelativePath>
                    <Name>Linux</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i314" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk Sweep\Libraries\Linux\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i7" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i315" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk Sweep\Libraries\LinuxRT</DestinationRelativePath>
                    <Name>LinuxRT</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i316" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk Sweep\Libraries\LinuxRT\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i8" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i317" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk Sweep\Libraries\Win32</DestinationRelativePath>
                    <Name>Win32</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i318" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk Sweep\Libraries\Win32\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i9" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i319" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk Sweep\Libraries\Win64</DestinationRelativePath>
                    <Name>Win64</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i320" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Crosstalk Sweep\Libraries\Win64\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i10" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i321" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Noise Sweep_Class D Amplifier</DestinationRelativePath>
                    <Name>Noise Sweep_Class D Amplifier</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i322" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Noise Sweep_Class D Amplifier\Noise Sweep_Class D Amplifier.aliases</DestinationRelativePath>
                    <Name>Noise Sweep_Class D Amplifier.aliases</Name>
                    <SourceItem z:Ref="i52" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i323" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Noise Sweep_Class D Amplifier\Noise Sweep_Class D Amplifier.exe</DestinationRelativePath>
                    <Name>Noise Sweep_Class D Amplifier.exe</Name>
                    <SourceItem z:Ref="i53" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i324" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Noise Sweep_Class D Amplifier\Noise Sweep_Class D Amplifier.ini</DestinationRelativePath>
                    <Name>Noise Sweep_Class D Amplifier.ini</Name>
                    <SourceItem z:Ref="i54" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i325" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Noise Sweep_Class D Amplifier\Noise Sweep_Class D Amplifier.serviceconfig</DestinationRelativePath>
                    <Name>Noise Sweep_Class D Amplifier.serviceconfig</Name>
                    <SourceItem z:Ref="i55" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i326" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Noise Sweep_Class D Amplifier\BuildUI</DestinationRelativePath>
                    <Name>BuildUI</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i327" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Noise Sweep_Class D Amplifier\BuildUI\Noise Sweep UI.lvlibp</DestinationRelativePath>
                    <Name>Noise Sweep UI.lvlibp</Name>
                    <SourceItem z:Ref="i47" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i328" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Noise Sweep_Class D Amplifier\Libraries</DestinationRelativePath>
                    <Name>Libraries</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i329" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Noise Sweep_Class D Amplifier\Libraries\Linux</DestinationRelativePath>
                    <Name>Linux</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i330" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Noise Sweep_Class D Amplifier\Libraries\Linux\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i48" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i331" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Noise Sweep_Class D Amplifier\Libraries\LinuxRT</DestinationRelativePath>
                    <Name>LinuxRT</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i332" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Noise Sweep_Class D Amplifier\Libraries\LinuxRT\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i49" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i333" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Noise Sweep_Class D Amplifier\Libraries\Win32</DestinationRelativePath>
                    <Name>Win32</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i334" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Noise Sweep_Class D Amplifier\Libraries\Win32\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i50" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i335" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Noise Sweep_Class D Amplifier\Libraries\Win64</DestinationRelativePath>
                    <Name>Win64</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i336" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Noise Sweep_Class D Amplifier\Libraries\Win64\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i51" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i337" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone Power Sweep</DestinationRelativePath>
                    <Name>Single Tone Power Sweep</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i338" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone Power Sweep\Single Tone Power Sweep.aliases</DestinationRelativePath>
                    <Name>Single Tone Power Sweep.aliases</Name>
                    <SourceItem z:Ref="i80" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i339" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone Power Sweep\Single Tone Power Sweep.exe</DestinationRelativePath>
                    <Name>Single Tone Power Sweep.exe</Name>
                    <SourceItem z:Ref="i81" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i340" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone Power Sweep\Single Tone Power Sweep.ini</DestinationRelativePath>
                    <Name>Single Tone Power Sweep.ini</Name>
                    <SourceItem z:Ref="i82" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i341" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone Power Sweep\Single Tone Power Sweep.serviceconfig</DestinationRelativePath>
                    <Name>Single Tone Power Sweep.serviceconfig</Name>
                    <SourceItem z:Ref="i83" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i342" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone Power Sweep\BuiltUI</DestinationRelativePath>
                    <Name>BuiltUI</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i343" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone Power Sweep\BuiltUI\Single Tone Power Sweep UI.lvlibp</DestinationRelativePath>
                    <Name>Single Tone Power Sweep UI.lvlibp</Name>
                    <SourceItem z:Ref="i75" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i344" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone Power Sweep\Libraries</DestinationRelativePath>
                    <Name>Libraries</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i345" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone Power Sweep\Libraries\Linux</DestinationRelativePath>
                    <Name>Linux</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i346" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone Power Sweep\Libraries\Linux\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i76" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i347" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone Power Sweep\Libraries\LinuxRT</DestinationRelativePath>
                    <Name>LinuxRT</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i348" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone Power Sweep\Libraries\LinuxRT\liblabview_grpc_server.so</DestinationRelativePath>
                    <Name>liblabview_grpc_server.so</Name>
                    <SourceItem z:Ref="i77" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i349" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone Power Sweep\Libraries\Win32</DestinationRelativePath>
                    <Name>Win32</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i350" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone Power Sweep\Libraries\Win32\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i78" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i351" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone Power Sweep\Libraries\Win64</DestinationRelativePath>
                    <Name>Win64</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i352" i:type="DistributionFileItem">
                    <DestinationRelativePath>[ProgramData]\National Instruments\MeasurementLink\Services\Class D Amplifier\Single Tone Power Sweep\Libraries\Win64\labview_grpc_server.dll</DestinationRelativePath>
                    <Name>labview_grpc_server.dll</Name>
                    <SourceItem z:Ref="i79" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
            </DistributionItems>
            <Name>Class D Amplifier MeasurementLink Plug-In</Name>
            <OutputDirectory>Packages</OutputDirectory>
            <PluginConfigurationOptions />
            <PrebuildAnalysisEnabled>true</PrebuildAnalysisEnabled>
            <Architecture>windows_x64</Architecture>
            <AutoIncrementVersion>Build</AutoIncrementVersion>
            <BuildStatus z:Id="i353">
                <BuildEverSuccessful>true</BuildEverSuccessful>
                <FileName>community-classdamplifier_1.0.0.25_windows_x64.nipkg</FileName>
                <Version>1.0.0.25</Version>
            </BuildStatus>
            <CompanyName>MyCompany</CompanyName>
            <CustomExecutes>
                <CustomExecute z:Id="i354">
                    <Arguments i:nil="true" />
                    <ExeName>AudioValidation\Utility\RegisterServices_Audio.exe</ExeName>
                    <HideConsoleWindow>true</HideConsoleWindow>
                    <IgnoreErrors>false</IgnoreErrors>
                    <RootLogicalName>[Program Files (64-bit)]</RootLogicalName>
                    <Schedule>Postall</Schedule>
                    <Step>Install</Step>
                    <Wait>false</Wait>
                </CustomExecute>
                <CustomExecute z:Id="i355">
                    <Arguments i:nil="true" />
                    <ExeName>AudioValidation\Utility\DeleteServices_Audio.exe</ExeName>
                    <HideConsoleWindow>true</HideConsoleWindow>
                    <IgnoreErrors>false</IgnoreErrors>
                    <RootLogicalName>[Program Files (64-bit)]</RootLogicalName>
                    <Schedule>Pre</Schedule>
                    <Step>Uninstall</Step>
                    <Wait>false</Wait>
                </CustomExecute>
            </CustomExecutes>
            <Description>Measurements for Class D amplifiers using MeasurementLink</Description>
            <DisplayName>Class D Amplifier MeasurementLink Plug-In</DisplayName>
            <FileName>community-classdamplifier_1.0.0.26_windows_x64.nipkg</FileName>
            <Homepage>https://github.com/NI-MeasurementLink-Plug-Ins/class-d-amplifier</Homepage>
            <MaintainerEmail>email@mycompany.com</MaintainerEmail>
            <MaintainerName>GitHub Community</MaintainerName>
            <Messages xmlns:d4p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
            <PackageName>community-classdamplifier</PackageName>
            <PackageRelationships>
                <PackageRelationship z:Id="i356">
                    <Constraint>LaterOrEqual</Constraint>
                    <DisplayName>LabVIEW Runtime (64-bit)</DisplayName>
                    <PackageName>ni-labview-2021-runtime-engine</PackageName>
                    <Relation>Depends</Relation>
                    <Version>21.1.2.49154-0+f2</Version>
                    <VersionType>AutoUpdate</VersionType>
                </PackageRelationship>
            </PackageRelationships>
            <ProductName>MyProduct</ProductName>
            <Section>Add-Ons</Section>
            <StoreProduct>true</StoreProduct>
            <Synopsis>community-classdamplifier</Synopsis>
            <Version>1.0.0.26</Version>
        </Distribution>
    </Distributions>
    <Feeds />
    <DistributionGroups>
        <DistributionGroup z:Id="i357">
            <Distributions>
                <Distribution z:Ref="i176" />
            </Distributions>
            <Name>Distribution Group</Name>
            <PrebuildAnalysisEnabled>true</PrebuildAnalysisEnabled>
            <StageDirectory>ProcessingStage</StageDirectory>
        </DistributionGroup>
    </DistributionGroups>
    <TestStandMode>true</TestStandMode>
    <PluginConfigurationOptions />
</Solution>